Name:           ros-melodic-vapor-master
Version:        0.1.0
Release:        0%{?dist}
Summary:        ROS vapor_master package

Group:          Development/Libraries
License:        Apache-2.0
URL:            http://github.com/roshub/vapor_master
Source0:        %{name}-%{version}.tar.gz

Requires:       nodejs
Requires:       ros-melodic-rospack
Requires:       ros-melodic-std-msgs
BuildRequires:  nodejs
BuildRequires:  npm
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-std-msgs

%description
ephemeral ros master node for cloudscale deployment

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Mon Dec 31 2018 Nicholas Zatkovich <nick@roshub.io> - 0.1.0-0
- Autogenerated by Bloom

